### ISSUE TITLE
404 Not found on /generate/url

### ISSUE THREAD

**Issue by Mrtenz** [MineSkin/api-php.mineskin.org#1]
I tried to use the API to generate a skin from a URL, but get a 404 on https://api.mineskin.org/generate/url.

**Comment by InventivetalentDev** [comment]
You need to use POST to access the _generate_ API.
I'd recommend [Advanced REST Client](https://chrome.google.com/webstore/detail/advanced-rest-client/hgmloofddffdnphfgcellkdfbfbjeloo) if you want to try it :)

**Comment by Mrtenz** [comment]
Then the API should return a 405 (Method not allowed), not a 404.

**Comment by Mrtenz** [comment]
Also, the API doesn't seem to work. It just keeps loading.
